# Path to your oh-my-zsh installation.
export ZSH=~wolfwzr/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"
#ZSH_THEME="wolf"
#ZSH_THEME="random"

DISABLE_UPDATE_PROMPT=true

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# plugins=(git)

# User configuration

export PATH="/home/wolfwzr/perl5/bin:/home/wolfwzr/perl5/bin:/usr/lib/mpi/gcc/openmpi/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/opt/kde3/bin:/usr/lib/mit/bin:/usr/lib/qt3/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/libexec:/opt/cross-mips32/bin:/sbin:/usr/sbin:/home/wolfwzr/usr/bin:/sbin:/usr/sbin:/home/wolfwzr/usr/bin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# Set vi-mode command line edit
bindkey -v
export KEYTIMEOUT=1
bindkey '^r' history-incremental-search-backward
# Ctrl-/ launch man page
bindkey '^_' run-help
bindkey '^Y' vi-put-before
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
#bindkey -s '^E' '^[I#^m'
bindkey '^n' down-history
bindkey '^p' up-history
bindkey -M viins '^f' vi-forward-word
bindkey -M viins '^b' vi-backward-word
bindkey -M viins '^a' vi-beginning-of-line
bindkey -M viins '^e' vi-end-of-line

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# use comments in interactive mode
setopt interactivecomments

compctl -g '*.tar.bz2 *.tar.gz *.bz2 *.gz *.jar *.rar *.tar *.tbz2 *.tgz *.zip *.Z *.a *.rpm *.deb *.ipk' \
      + -g '(-/)' ex

functions user-complete (){
    if [[ -n $BUFFER ]] ; then     # 如果该行有内容
        zle expand-or-complete     # 执行 TAB 原来的功能
    else                           # 如果没有
        BUFFER="cd "               # 填入 cd（空格）
        zle end-of-line            # 这时光标在行首，移动到行末
        zle expand-or-complete     # 执行 TAB 原来的功能
    fi }
zle -N user-complete
bindkey "\t" user-complete         #将上面的功能绑定到 TAB 键

function sudo-command-line () {
    [[ -z $BUFFER ]] && zle up-history
    [[ $BUFFER != sudo\ * ]] && BUFFER="sudo $BUFFER"
	#光标移动到行末
    zle end-of-line
}
zle -N sudo-command-line
bindkey '^\' sudo-command-line

function comment-command-line () {
    [[ -z $BUFFER ]] && zle up-history
    [[ $BUFFER != \#\ * ]] && BUFFER="# $BUFFER"
	#光标移动到行末
    zle end-of-line
	zle -U ''
}
zle -N comment-command-line
#bindkey '^E' comment-command-line

function open-current-folder() {
    xdg-open .
}
zle -N open-current-folder
bindkey '^o' open-current-folder

bindkey -s '^g' 'ls^M'
bindkey -s '^j' 'cd -^M'
bindkey -s '^k' 'cd ..^M'

source /etc/wolfwzr.bashrc
alias src='source ~/.zshrc'

# history options
HISTSIZE=50000
SAVEHIST=50000
# 不保留重复的历史记录项
setopt hist_ignore_all_dups
## 在命令前添加空格，不将此命令添加到记录文件中
setopt hist_ignore_space
# 写入历史记录文件时使用 fcntl，可以提高写文件性能，尤其是在 NFS 下
# zsh 4.3.6 doesn't have this option
setopt hist_fcntl_lock 2>/dev/null
setopt hist_reduce_blanks
# 不共享历史记录，只在shell退出时同步历史记录
# 这样各个shell运行期的历史记录就相对独立
setopt noshare_history
setopt append_history

alias -s jpg=xview
alias -s jpeg=xview
alias -s png=xview
alias -s pdf=o
alias -s exe=wine

[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && source ~/.autojump/etc/profile.d/autojump.sh
autoload -U compinit && compinit -u
